package be.condorcet.mavenprojectjqm;
// Generated 28-sept.-2019 18:57:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApiCours generated by hbm2java
 */
public class ApiCours  implements java.io.Serializable {


     private int idcours;
     private String matiere;
     private short heures;
     private Set apiSessioncourses = new HashSet(0);

    public ApiCours() {
    }

	
    public ApiCours(int idcours, String matiere, short heures) {
        this.idcours = idcours;
        this.matiere = matiere;
        this.heures = heures;
    }
    public ApiCours(int idcours, String matiere, short heures, Set apiSessioncourses) {
       this.idcours = idcours;
       this.matiere = matiere;
       this.heures = heures;
       this.apiSessioncourses = apiSessioncourses;
    }
   
    public int getIdcours() {
        return this.idcours;
    }
    
    public void setIdcours(int idcours) {
        this.idcours = idcours;
    }
    public String getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(String matiere) {
        this.matiere = matiere;
    }
    public short getHeures() {
        return this.heures;
    }
    
    public void setHeures(short heures) {
        this.heures = heures;
    }
    public Set getApiSessioncourses() {
        return this.apiSessioncourses;
    }
    
    public void setApiSessioncourses(Set apiSessioncourses) {
        this.apiSessioncourses = apiSessioncourses;
    }




}


