package be.condorcet.mavenprojectjqm;
// Generated 28-sept.-2019 18:57:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApiFormateur generated by hbm2java
 */
public class ApiFormateur  implements java.io.Serializable {


     private int idform;
     private String matricule;
     private String nom;
     private String prenom;
     private String numero;
     private String rue;
     private String localite;
     private short cp;
     private String tel;
     private Set apiInfoses = new HashSet(0);

    public ApiFormateur() {
    }

	
    public ApiFormateur(int idform, String matricule, String nom, String prenom, String numero, String rue, String localite, short cp, String tel) {
        this.idform = idform;
        this.matricule = matricule;
        this.nom = nom;
        this.prenom = prenom;
        this.numero = numero;
        this.rue = rue;
        this.localite = localite;
        this.cp = cp;
        this.tel = tel;
    }
    public ApiFormateur(int idform, String matricule, String nom, String prenom, String numero, String rue, String localite, short cp, String tel, Set apiInfoses) {
       this.idform = idform;
       this.matricule = matricule;
       this.nom = nom;
       this.prenom = prenom;
       this.numero = numero;
       this.rue = rue;
       this.localite = localite;
       this.cp = cp;
       this.tel = tel;
       this.apiInfoses = apiInfoses;
    }
   
    public int getIdform() {
        return this.idform;
    }
    
    public void setIdform(int idform) {
        this.idform = idform;
    }
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getRue() {
        return this.rue;
    }
    
    public void setRue(String rue) {
        this.rue = rue;
    }
    public String getLocalite() {
        return this.localite;
    }
    
    public void setLocalite(String localite) {
        this.localite = localite;
    }
    public short getCp() {
        return this.cp;
    }
    
    public void setCp(short cp) {
        this.cp = cp;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Set getApiInfoses() {
        return this.apiInfoses;
    }
    
    public void setApiInfoses(Set apiInfoses) {
        this.apiInfoses = apiInfoses;
    }




}


