package be.condorcet.mavenprojectjqm;
// Generated 28-sept.-2019 18:57:42 by Hibernate Tools 4.3.1



/**
 * ApiInfos generated by hbm2java
 */
public class ApiInfos  implements java.io.Serializable {


     private int idInfos;
     private ApiFormateur apiFormateur;
     private ApiSessioncours apiSessioncours;
     private short nh;

    public ApiInfos() {
    }

    public ApiInfos(int idInfos, ApiFormateur apiFormateur, ApiSessioncours apiSessioncours, short nh) {
       this.idInfos = idInfos;
       this.apiFormateur = apiFormateur;
       this.apiSessioncours = apiSessioncours;
       this.nh = nh;
    }
   
    public int getIdInfos() {
        return this.idInfos;
    }
    
    public void setIdInfos(int idInfos) {
        this.idInfos = idInfos;
    }
    public ApiFormateur getApiFormateur() {
        return this.apiFormateur;
    }
    
    public void setApiFormateur(ApiFormateur apiFormateur) {
        this.apiFormateur = apiFormateur;
    }
    public ApiSessioncours getApiSessioncours() {
        return this.apiSessioncours;
    }
    
    public void setApiSessioncours(ApiSessioncours apiSessioncours) {
        this.apiSessioncours = apiSessioncours;
    }
    public short getNh() {
        return this.nh;
    }
    
    public void setNh(short nh) {
        this.nh = nh;
    }




}


