package be.condorcet.mavenprojectjqm;
// Generated 28-sept.-2019 18:57:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ApiLocal generated by hbm2java
 */
public class ApiLocal  implements java.io.Serializable {


     private int idlocal;
     private String sigle;
     private short places;
     private String description;
     private Set apiSessioncourses = new HashSet(0);

    public ApiLocal() {
    }

	
    public ApiLocal(int idlocal, String sigle, short places, String description) {
        this.idlocal = idlocal;
        this.sigle = sigle;
        this.places = places;
        this.description = description;
    }
    public ApiLocal(int idlocal, String sigle, short places, String description, Set apiSessioncourses) {
       this.idlocal = idlocal;
       this.sigle = sigle;
       this.places = places;
       this.description = description;
       this.apiSessioncourses = apiSessioncourses;
    }
   
    public int getIdlocal() {
        return this.idlocal;
    }
    
    public void setIdlocal(int idlocal) {
        this.idlocal = idlocal;
    }
    public String getSigle() {
        return this.sigle;
    }
    
    public void setSigle(String sigle) {
        this.sigle = sigle;
    }
    public short getPlaces() {
        return this.places;
    }
    
    public void setPlaces(short places) {
        this.places = places;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getApiSessioncourses() {
        return this.apiSessioncourses;
    }
    
    public void setApiSessioncourses(Set apiSessioncourses) {
        this.apiSessioncourses = apiSessioncourses;
    }




}


