package be.condorcet.mavenprojectjqm;
// Generated 28-sept.-2019 18:57:42 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ApiSessioncours generated by hbm2java
 */
public class ApiSessioncours  implements java.io.Serializable {


     private int idsesscours;
     private ApiCours apiCours;
     private ApiLocal apiLocal;
     private Date datedebut;
     private Date datefin;
     private short nbreinscrits;
     private Set apiInfoses = new HashSet(0);

    public ApiSessioncours() {
    }

	
    public ApiSessioncours(int idsesscours, ApiCours apiCours, ApiLocal apiLocal, Date datedebut, Date datefin, short nbreinscrits) {
        this.idsesscours = idsesscours;
        this.apiCours = apiCours;
        this.apiLocal = apiLocal;
        this.datedebut = datedebut;
        this.datefin = datefin;
        this.nbreinscrits = nbreinscrits;
    }
    public ApiSessioncours(int idsesscours, ApiCours apiCours, ApiLocal apiLocal, Date datedebut, Date datefin, short nbreinscrits, Set apiInfoses) {
       this.idsesscours = idsesscours;
       this.apiCours = apiCours;
       this.apiLocal = apiLocal;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.nbreinscrits = nbreinscrits;
       this.apiInfoses = apiInfoses;
    }
   
    public int getIdsesscours() {
        return this.idsesscours;
    }
    
    public void setIdsesscours(int idsesscours) {
        this.idsesscours = idsesscours;
    }
    public ApiCours getApiCours() {
        return this.apiCours;
    }
    
    public void setApiCours(ApiCours apiCours) {
        this.apiCours = apiCours;
    }
    public ApiLocal getApiLocal() {
        return this.apiLocal;
    }
    
    public void setApiLocal(ApiLocal apiLocal) {
        this.apiLocal = apiLocal;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }
    public short getNbreinscrits() {
        return this.nbreinscrits;
    }
    
    public void setNbreinscrits(short nbreinscrits) {
        this.nbreinscrits = nbreinscrits;
    }
    public Set getApiInfoses() {
        return this.apiInfoses;
    }
    
    public void setApiInfoses(Set apiInfoses) {
        this.apiInfoses = apiInfoses;
    }




}


